trigger:
  branches:
    include:
    - main
  paths:
    include:
    - sscgi_public_facing/*
    - SSCGI_WEBSITE_ADMIN-FE/*
pr:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '20.x'
    - task: CmdLine@2
      displayName: 'Install npm dependencies for sscgi_public_facing'
      inputs:
        script: |
          npm install
        workingDirectory: $(Build.SourcesDirectory)/sscgi_public_facing
    - task: CmdLine@2
      displayName: 'Build Artifacts for sscgi_public_facing'
      inputs:
        script: |
          npx ng build --output-path=$(Build.ArtifactStagingDirectory)/sscgi_public_facing
        workingDirectory: $(Build.SourcesDirectory)/sscgi_public_facing
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/sscgi_public_facing'
        artifactName: 'sscgi_public_facing_build'
      displayName: 'Publish Build Artifact for sscgi_public_facing'

