trigger:
  branches:
    include:
    - main
  paths:
    include:
    - SSCGI_WEBSITE_ADMIN-FE/*
pool:
  vmImage: 'windows-latest'
  
steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
- task: CmdLine@2
  displayName: 'Install npm dependencies for SSCGI_WEBSITE_ADMIN-FE'
  inputs:
    script: |
      npm install
    workingDirectory: $(Build.SourcesDirectory)/SSCGI_WEBSITE_ADMIN-FE
- task: CmdLine@2
  displayName: 'Build Artifacts for SSCGI_WEBSITE_ADMIN-FE'
  inputs:
    script: |
      npx ng build --output-path=$(Build.ArtifactStagingDirectory)/SSCGI_WEBSITE_ADMIN-FE
    workingDirectory: $(Build.SourcesDirectory)/SSCGI_WEBSITE_ADMIN-FE
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/SSCGI_WEBSITE_ADMIN-FE'
    artifactName: 'SSCGI_WEBSITE_ADMIN-FE_build'
  displayName: 'Publish Build Artifact for SSCGI_WEBSITE_ADMIN-FE'

